- src/Commands/SpladeInstallCommand.php
- src/Facades/Splade.php
`vendor/bin/phpstan analyze -c vendor/nunomaduro/larastan/extension.neon -l 5 src/` 🤩
> Fix problems reported by PHPStan

- app/package-lock.json
- app/resources/views/modal/two.blade.php
- app/tests/Browser/ModalTest.php
- lib/Components/Modal.vue
- package-lock.json
- resources/views/modal-wrapper.blade.php
- resources/views/modal.blade.php
- resources/views/slideover.blade.php
- src/Components/Modal.php
- src/Components/ModalWrapper.php
Can be disabled with `<x-splade-modal :close-button="false">`
> Default close button for Modal and Slideover (#14)

- app/package-lock.json
- app/resources/js/app.js
- lib/Splade.js
- lib/SpladePlugin.js
- lib/SpladeProgress.js
- package-lock.json
- package.json
- stubs/resources/js/app.js
- vite.config.js
> Progress bar

- app/app/Http/Controllers/TwoFieldsFormController.php
- app/resources/views/form/submitOnChange.blade.php
- app/routes/web.php
- app/tests/Browser/Form/SubmitOnChangeTest.php
- composer.json
- lib/Components/Form.vue
- resources/views/form.blade.php
- src/Components/Form.php
Watch all values:
```
<x-splade-form submit-on-change>
```
Watch a single value:
```
<x-splade-form submit-on-change="name">
```
Watch multiple values (string input):
```
<x-splade-form submit-on-change="name, email">
```
Watch multiple values (array input):
```
<x-splade-form :submit-on-change="['name', 'email']">
```
> Form submit on change

- app/tests/Unit/SpladeTableTest.php
- src/SpladeTable.php
> Default sort improvement

- app/app/Http/Controllers/TableController.php
- app/routes/web.php
- app/tests/Browser/FormLibrariesInModalTest.php
- app/tests/Browser/Table/CaseTest.php
- app/tests/Browser/Table/CustomTest.php
- app/tests/Browser/Table/DropdownTest.php
- app/tests/Browser/Table/FilterTest.php
- app/tests/Browser/Table/PaginationTest.php
- app/tests/Browser/Table/RowLinkTest.php
- app/tests/Browser/Table/SortTest.php
- app/tests/DuskTestCase.php
- src/SpladeQueryBuilder.php
- src/SpladeTable.php
- src/Table/HasResource.php
> Resolve Row Links after the resource has been loaded

- app/app/Http/Controllers/NavigationController.php
- app/resources/views/navigation/nav.blade.php
- app/routes/web.php
- app/tests/Browser/NavigationTest.php
- lib/Components/Link.vue
- resources/views/link.blade.php
- src/Components/Link.php
- src/ServiceProvider.php
> Allow Link component to post data

- README.md
this will fix the github test badge icon.
> fix github test badge icon

- app/app/Http/Controllers/TableController.php
- app/resources/views/table/modal.blade.php
- app/resources/views/table/users.blade.php
- app/routes/web.php
- app/tests/Browser/Table/ModalTest.php
- lib/Components/Link.vue
- lib/Components/Modal.vue
- lib/Components/Table.vue
- lib/Splade.js
- lib/SpladeApp.vue
- resources/views/components/modal-wrapper.blade.php
- resources/views/components/modal.blade.php
- resources/views/table/head.blade.php
- resources/views/table/pagination.blade.php
- resources/views/table/simple-pagination.blade.php
- resources/views/table/table.blade.php
- resources/views/table/wrapper.blade.php
- src/Http/SpladeMiddleware.php
- src/SpladeCore.php
> Allow Table component in Modal + Modal position attribute

- app/tests/Unit/SpladeCoreTest.php
- src/SpladeCore.php
> Support for custom exception render callback

- app/app/Http/Controllers/TableController.php
- app/resources/views/table/preserveScrollForm.blade.php
- app/routes/web.php
- app/tests/Browser/Table/PreserveScrollTest.php
- lib/Components/Form.vue
- lib/Components/Link.vue
- lib/Splade.js
- resources/views/functional/form.blade.php
- src/Components/Form.php
- src/Facades/Splade.php
- src/Http/SpladeMiddleware.php
- src/SpladeCore.php
> Preserve scroll on submit

- lib/Splade.js
> Fix for replacing the URL of the current page

- resources/lang/pt_BR.json
- resources/lang/pt_PT.json
Added translations files for pt_BR and pt_PT
> Added pt_BR and pt_PT translations

- resources/lang/ja.json
> Add Japanese Translation

- resources/lang/ar.json
Added translations files for Arabic ar
> add Arabic ar translation

- resources/lang/it.json
Added translation file for Italian language
> Created Italian translation file

- .github/workflows/run-stub-tests.yml
- .github/workflows/run-table-tests.yml
- .github/workflows/run-tests.yml
- composer.json
- updated composer.json
- updated tests
> Add support for Laravel 10

- resources/lang/ne.json
Added Nepali ne translation file.
> Add Nepali ne translation to Splade

- resources/lang/es.json
Added fields (Reset and Remove search) - Spanish translations
> Added fields (Reset and Remove search)

- resources/lang/fil.json
This PR adds Filipino (fil) translation.
> Add Filipino (fil) translation

- app/app/Tables/Projects.php
- resources/views/table/body.blade.php
- resources/views/table/head.blade.php
- src/Table/Column.php
- src/Table/HasColumns.php
This PR allows to change the alignment of table columns:
```php
$table
->column('name', alignment: 'left')
->column('postcode', alignment: 'center')
->column('actions', alignment: 'right');
```
> Table alignment

- app/app/Http/Controllers/ToastController.php
- resources/views/components/toast.blade.php
- src/SpladeCore.php
- src/SpladeToast.php
> Support for `HtmlString` in Toasts
